In [1]:
# importing modules
import pandas as pd
import re
from requests import get
from bs4 import BeautifulSoup

# getting url and converting into bs4 element
url = "https://www.helpscout.com/about/"
response = get(url)
html_soup = BeautifulSoup(response.text, 'html.parser')

# finding all members tag
members = html_soup.find_all('h5', class_ = 'tx-14 u-mrg-0 tx-500')
name = []
for m in members:
    name.append(m.text)

    
# formatting names
names = []
for n in name:
    n = n.replace("\n","")
    n = n.replace("    ","")
    names.append(n)
    
    
# finding all title tag
title = html_soup.find_all('p', class_ = 'tx-12 t-tx-charcoal-400 u-mrg-0')
position = []
for pos in title:
    position.append(pos.text)
    

# formatting output
positions = []
for p in position:
    p = p.replace("\n", "")
    p = p.replace("    ","")
    positions.append(p)
    

# finding locations
loc = []
location = html_soup.find_all('p', class_ = 'c-teammate__location t-tx-charcoal-400 tx-10 tx-uppercase u-mrg-0')

for l in location:
    loc.append(l.text)

    
# formatting output of loc
locs = []
for l in loc:
    l = l.replace("\n\n\n   ","")
    l = l.replace("\n ","")
    locs.append(l)
    
    
    
# saving data as pandas dataframe
helpscout_data = pd.DataFrame({'names': names,
                               'Title': positions,
                               'location': locs,
                              })
helpscout_data.to_csv('helpscout.csv')

# checking data
helpscout_data.head()

                  names                              Title          location
0    Abigail Phillips                    Customer Champion   Somerville, MA
1    Adrianne Hersrud                    Customer Champion      Seattle, WA
2  Agata Niewiadomska                    Customer Champion   Krakow, Poland
3       Alison Groves    Customer Champion @alisongroves      Nashville, TN
4        Anthony Gass        Customer Champion @agass603         Durham, NH